// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEBAPI_LAB_2.Models;

#nullable disable

namespace WEBAPI_LAB_2.Migrations
{
    [DbContext(typeof(CourseContext))]
    [Migration("20241208144253_v3")]
    partial class v3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WEBAPI_LAB_2.Models.Course", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Crs_description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Crs_name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Course");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Crs_description = ".Net",
                            Crs_name = ".Net",
                            Duration = 96
                        },
                        new
                        {
                            ID = 2,
                            Crs_description = "HTML",
                            Crs_name = "HTML",
                            Duration = 70
                        },
                        new
                        {
                            ID = 3,
                            Crs_description = "CSS",
                            Crs_name = "CSS",
                            Duration = 63
                        },
                        new
                        {
                            ID = 4,
                            Crs_description = "JS",
                            Crs_name = "JS",
                            Duration = 40
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
